>Notes
- ctrl+j for terminal
- dont make a file name as library name , e.g, Numpy.ipynb
-----


In [3]:
import numpy as np

In [4]:
lst = [3,4,2,6,8,9]
print(lst)
print(type(lst))
#list converts into array
arr = np.array(lst)
print(arr)
print(type(arr))
c = arr[0]+arr[3]
print(c)

[3, 4, 2, 6, 8, 9]
<class 'list'>
[3 4 2 6 8 9]
<class 'numpy.ndarray'>
9


In [5]:
#directly creating an array
arr1= np.array({1,2,3,4,5,6})
print(arr1)
print(type(arr1))

{1, 2, 3, 4, 5, 6}
<class 'numpy.ndarray'>


In [7]:
np.__version__ #checking version of numpy

'2.4.0'

In [8]:
lst = list(range(0,21))

In [9]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [10]:
np.array(lst)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
arr = np.arange(40) #arange works as range

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [ ]:
arr = np.zeros(5) #create array with values 0

In [16]:
arr

array([0., 0., 0., 0., 0.])

In [17]:
arr = np.ones(9) #create array with values 1

In [18]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
arr = np.ones((5 ,10)) #create 2D array

In [28]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr =  np.linspace(1,10,5) #created random array of 5 elements btw 1-10

In [30]:
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
arr = np.arange(60).reshape(12,5) #12 row,5 column , reshape function changes the shape of array 
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr = np.arange(50).reshape(10,5) #10 row,5 column , reshape function changes the shape of array 
arr #10*5 = 50

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
arr = np.random.randint(6000) #randomly generate a value
arr

2084

In [40]:
arr = np.random.randint(1,100,7) #randomly generate a array of 7 size
arr

array([14, 86, 62, 34, 76, 41, 86], dtype=int32)

In [42]:
arr = np.random.random(10) #randomly generate 10 elements btw 0-1
arr

array([0.84996359, 0.8507778 , 0.52059876, 0.38167574, 0.65052383,
       0.27900727, 0.01682512, 0.24545318, 0.31419302, 0.24444313])

In [4]:
arr = np.arange(60).reshape(12,5) #12 row,5 column , reshape function changes the shape of array 
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [47]:
arr.shape #shape of array

(12, 5)

In [ ]:
arr.ndim #array dimensions

2

In [ ]:
arr.size #size of array

60

In [53]:
arr.dtype #array data types

dtype('int64')

In [51]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr[0] #first row

array([0, 1, 2, 3, 4])

In [ ]:
arr[0][0] #first element

np.int64(0)

In [57]:
print(arr[0][0] )
arr[1][3]

0


np.int64(8)

In [ ]:
arr[0:3] #first three rows,last index not counts

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr[0:3,0:2] #three rows , two columns

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [ ]:
arr[0:3][0:2] #first - three rows of arr , then it's two rows 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

*In NumPy, chained slicing like arr[a][b] slices rows twice.
Use arr[a, b] to slice rows and columns together.*

In [ ]:
arr[11][4] #last element

np.int64(59)

In [62]:
arr[11][-1] #last element

np.int64(59)

In [63]:
arr[-1][-1] #last element

np.int64(59)

In [64]:
arr[-1][4] #last element

np.int64(59)

In [ ]:
arr[11][4] =100 #last element updating value

In [66]:
arr[11][4] #last element

np.int64(100)

In [67]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 100]])

In [68]:
arr.shape

(12, 5)

In [ ]:
arr.T #changed shape into 5,12 , transpose 

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55],
       [  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56],
       [  2,   7,  12,  17,  22,  27,  32,  37,  42,  47,  52,  57],
       [  3,   8,  13,  18,  23,  28,  33,  38,  43,  48,  53,  58],
       [  4,   9,  14,  19,  24,  29,  34,  39,  44,  49,  54, 100]])

In [6]:
arr = np.arange(225).reshape(15,3,5) #15=frames,3=rows,5=columns , generate a threeD array

In [88]:
arr

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]],

       [[ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104]],

       [[105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119]],

       [[120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134]],

       [[135, 136, 137, 138, 139],
  

In [ ]:
arr[0] #first frame matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr[0][2] #first frame matrix ka 2nd index row complete

array([10, 11, 12, 13, 14])

In [ ]:
arr[0,0:5,-1] #printed first frame ka ,4th row me[here 3 rows only ,so 0:5 → actually becomes 0:3] ,from each row select last column element

array([ 4,  9, 14])

In [ ]:
arr[0:4,0:2,1] #from first four frames,select first two rows, and 1th index column elements

array([[ 1,  6],
       [16, 21],
       [31, 36],
       [46, 51]])

In [93]:
# arr = [1,2,3,4,5]
# arr1= [2,5,7,8,9]
# print(arr*arr1) cant multiply lists

In [ ]:
arr = np.array([1,2,3,4,5])
arr1= np.array([2,5,7,8,9]) #conversion into array then it works [vectorized operation]
print(arr*arr1) 

[ 2 10 21 32 45]


In [95]:
arr+arr1

array([ 3,  7, 10, 12, 14])

In [96]:
arr-arr1

array([-1, -3, -4, -4, -4])

In [97]:
arr1/arr

array([2.        , 2.5       , 2.33333333, 2.        , 1.8       ])

In [ ]:
arr1.sort() #just sort array in ascending order

In [105]:
arr


array([1, 2, 3, 4, 5])

#### 2D ARRAY TO 1D ARRAY 
``` .ravel() , .flatten() ```

In [7]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [8]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

```ravel()```
- Returns a 1-D view of the original array (if possible)
- No new memory allocation (most of the time)
- Changes in result may affect original array

In [9]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

```flatten()```
- Returns a 1-D copy
- Uses extra memory
- Changes do NOT affect original array

In [10]:
#Bonus way
arr.reshape(-1)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

##### `reshape(-1)` flattens an array into one dimension by automatically inferring the required size.